spring:
  datasource:
    url: jdbc:mysql://mbslaw-db.cszatmtp17tv.ap-northeast-2.rds.amazonaws.com:3306/ye?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true
    username: ye
    password: 'M_5%Aw?A!G'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: mysql-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    allow-bean-definition-overriding: true
    database-platform: org.hibernate.dialect.MySQL8Dialect